-- INSERT INTO board_tb (title, content, username, created_at) VALUES ('제목1', '내용1', 'ssar', NOW());
-- INSERT INTO board_tb (title, content, username, created_at) VALUES ('제목2', '내용2', 'ssar', NOW());
-- INSERT INTO board_tb (title, content, username, created_at) VALUES ('제목3', '내용3', 'cos', NOW());
-- INSERT INTO board_tb (title, content, username, created_at) VALUES ('제목4', '내용4', 'love', NOW());